name:                prover
version:             0.1.0.0
github:              "githubuser/prover"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prover#readme>

dependencies:
- aeson >= 1.4.6.0 && < 2
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2 && < 1
- hashable >= 1.2.7.0 && < 2
- megaparsec >= 7.0.5 && < 8
- mtl >= 2.2.2 && < 3
- parser-combinators >= 1.1.0 && < 2
- pretty-simple >= 2.2.0.1 && < 3
- text >= 1.2.3.1 && < 2
- unordered-containers >= 0.2.10.0 && < 1

executables:
  prover:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
